/// This is the heavily modified output of a tool

using System.Xml.Serialization;
using System;
#pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Goedel.Document.RFC; 

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public abstract class Common {
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
    public string lang { get; set; }


    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
    public string @base { get; set; }
    }

///<summary>The common enumeration for all tagged text run types</summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
public enum ItemsChoiceTextRun {

    /// <remarks/>
    [XmlEnum(Name = "artwork")]
    Artwork,

    /// <remarks/>
    [XmlEnum(Name = "bcp14")]
    Bcp14,

    /// <remarks/>
    [XmlEnum(Name = "cref")]
    Cref,

    /// <remarks/>
    [XmlEnum(Name = "dl")]
    Dl,

    /// <remarks/>
    [XmlEnum(Name = "em")]
    Em,

    /// <remarks/>
    [XmlEnum(Name = "eref")]
    Eref,

    /// <remarks/>
    [XmlEnum(Name = "figure")]
    Figure,

    /// <remarks/>
    [XmlEnum(Name = "iref")]
    Iref,

    /// <remarks/>
    [XmlEnum(Name = "list")]
    List,

    /// <remarks/>
    [XmlEnum(Name = "ol")]
    Ol,

    /// <remarks/>
    [XmlEnum(Name = "relref")]
    Relref,

    /// <remarks/>
    [XmlEnum(Name = "sourcecode")]
    Sourcecode,

    /// <remarks/>
    [XmlEnum(Name = "strong")]
    Strong,

    /// <remarks/>
    [XmlEnum(Name = "sub")]
    Sub,

    /// <remarks/>
    [XmlEnum(Name = "sup")]
    Sup,
    
    /// <remarks/>
    [XmlEnum(Name = "t")]
    T,
    
    /// <remarks/>
    [XmlEnum(Name = "tt")]
    Tt,
    
    /// <remarks/>
    [XmlEnum(Name = "ul")]
    Ul,
    
    /// <remarks/>
    [XmlEnum(Name = "xref")]
    Xref,
    
    /// <remarks/>
    [XmlEnum(Name = "spanx")]
    Spanx,
    
    /// <remarks/>
    [XmlEnum(Name = "vspace")]
    Vspace,
    
    /// <remarks/>
    [XmlEnum(Name = "aside")]
    Aside,
    
    /// <remarks/>
    [XmlEnum(Name = "table")]
    Table,
    
    /// <remarks/>
    [XmlEnum(Name = "texttable")]
    Texttable,
    
    /// <remarks/>
    [XmlEnum(Name = "blockquote")]
    Blockquote,
    }



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
#region // rfc
public partial class rfc : Common {


    public rfc() {
        this.obsoletes = "";
        this.updates = "";
        this.consensus = rfcConsensus.False;
        this.submissionType = streamType.IETF;
        this.sortRefs = boolean.False;
        this.symRefs = boolean.True;
        this.tocInclude = boolean.True;
        this.tocDepth = "3";
        this.indexInclude = rfcIndexInclude.False;
        this.scripts = "Common,Latin";
        }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("link")]
    public link[] link { get; set; }

    /// <remarks/>
    public front front { get; set; }

    /// <remarks/>
    public middle middle { get; set; }

    /// <remarks/>
    public back back { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string number { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string obsoletes { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string updates { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string category { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(rfcConsensus.False)]
    public rfcConsensus consensus { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string seriesNo { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ipr { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "IDREF")]
    public string iprExtract { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(streamType.IETF)]
    public streamType submissionType { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string docName { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.False)]
    public boolean sortRefs { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.True)]
    public boolean symRefs { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.True)]
    public boolean tocInclude { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("3")]
    public string tocDepth { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string prepTime { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(rfcIndexInclude.False)]
    public rfcIndexInclude indexInclude { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Common,Latin")]
    public string scripts { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string expiresDate { get; set; }
    }

#endregion
#region // Link

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class link : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string href { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rel { get; set; }
    }

#endregion
#region // Front

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class front : Common {

    /// <remarks/>
    public title title { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("seriesInfo")]
    public seriesInfo[] seriesInfo { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("author")]
    public author[] author { get; set; }

    /// <remarks/>
    public date date { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("area")]
    public asciitext[] area { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("workgroup")]
    public asciitext[] workgroup { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("keyword")]
    public asciitext[] keyword { get; set; }

    /// <remarks/>
    public @abstract @abstract { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("note")]
    public note[] note { get; set; }

    /// <remarks/>
    public boilerplate boilerplate { get; set; }
    }

#endregion
#region // Title

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class title : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string abbrev { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ascii { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value { get; set; }
    }

#endregion
#region // Seriesinfo

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class seriesInfo {

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string asciiName { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string asciiValue { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string status { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(streamType.IETF)]
    public streamType stream { get; set; } = streamType.IETF;
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum streamType {

    /// <remarks/>
    [XmlEnum(Name = "IETF")] 
    IETF,

    /// <remarks/>
    [XmlEnum(Name = "IAB")]
    IAB,

    /// <remarks/>
    [XmlEnum(Name = "IRTF")]
    IRTF,

    /// <remarks/>
    [XmlEnum(Name = "independent")]
    Independent,
    }
#endregion
#region // Author
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class author : Common {

    /// <remarks/>
    public organization organization { get; set; }

    /// <remarks/>
    public address address { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string initials { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string asciiInitials { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string surname { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fullname { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public authorRole role { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool roleSpecified { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string asciiFullname { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class organization : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string abbrev { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ascii { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class address : Common {
    /// <remarks/>
    public postal postal { get; set; }

    /// <remarks/>
    public asciitext phone { get; set; }

    /// <remarks/>
    public asciitext facsimile { get; set; }

    /// <remarks/>
    public asciitext email { get; set; }

    /// <remarks/>
    public asciitext uri { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class postal : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("city", typeof(taggedtext))]
    [System.Xml.Serialization.XmlElementAttribute("code", typeof(taggedtext))]
    [System.Xml.Serialization.XmlElementAttribute("country", typeof(taggedtext))]
    [System.Xml.Serialization.XmlElementAttribute("postalLine", typeof(taggedtext))]
    [System.Xml.Serialization.XmlElementAttribute("region", typeof(taggedtext))]
    [System.Xml.Serialization.XmlElementAttribute("street", typeof(taggedtext))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public taggedtext[] Items { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute()]
[System.Xml.Serialization.XmlRootAttribute("street", IsNullable = false)]
public partial class taggedtext : Common {
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ascii { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
public enum ItemsChoiceType {

    /// <remarks/>
    [XmlEnum(Name = "city")]
    City,

    /// <remarks/>
    [XmlEnum(Name = "code")]
    Code,

    /// <remarks/>
    [XmlEnum(Name = "country")]
    Country,

    /// <remarks/>
    [XmlEnum(Name = "postalLine")]
    PostalLine,

    /// <remarks/>
    [XmlEnum(Name = "region")]
    Region,

    /// <remarks/>
    [XmlEnum(Name = "street")]
    Street,
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute()]
[System.Xml.Serialization.XmlRootAttribute("phone", IsNullable = false)]
public partial class asciitext : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string abbrev { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum authorRole {

    /// <remarks/>
    [XmlEnum(Name = "editor")]
    Editor,
    }
#endregion
#region // Date
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class date : Common {
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string day { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string month { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string year { get; set; }
    }

#endregion
#region // Abstract

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class @abstract : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dl", typeof(dl))]
    [System.Xml.Serialization.XmlElementAttribute("ol", typeof(ol))]
    [System.Xml.Serialization.XmlElementAttribute("t", typeof(t))]
    [System.Xml.Serialization.XmlElementAttribute("ul", typeof(ul))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceTextRun[] ItemsElementName { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }


    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pn { get; set; }

    }
#endregion
#region // Lists - DL

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class dl : Common {

    [System.Xml.Serialization.XmlElementAttribute("dt", typeof(listItemType))]
    [System.Xml.Serialization.XmlElementAttribute("dd", typeof(listItemType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {get; set;}

    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceTypeDL[] ItemsElementName { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(dlSpacing.Normal)]
    public dlSpacing spacing { get; set; } = dlSpacing.Normal;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.True)]
    public boolean hanging { get; set; } = boolean.True;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pn { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
public enum ItemsChoiceTypeDL {
    /// <remarks/>
    [XmlEnum(Name = "dt")]
    Dt,

    /// <remarks/>
    [XmlEnum(Name = "dd")]
    Dd
    }


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute()]
[System.Xml.Serialization.XmlRootAttribute("li", IsNullable = false)]
public partial class listItemType : Common {
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(typeof(string))]

    [System.Xml.Serialization.XmlElementAttribute("bcp14", typeof(Bcp14String))]
    [System.Xml.Serialization.XmlElementAttribute("strong", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("sub", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("sup", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("tt", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("em", typeof(textrun))]

    [System.Xml.Serialization.XmlElementAttribute("t", typeof(t))]
    [System.Xml.Serialization.XmlElementAttribute("dl", typeof(dl))]
    [System.Xml.Serialization.XmlElementAttribute("ul", typeof(ul))]
    [System.Xml.Serialization.XmlElementAttribute("list", typeof(list))]
    [System.Xml.Serialization.XmlElementAttribute("ol", typeof(ol))]

    [System.Xml.Serialization.XmlElementAttribute("artwork", typeof(artwork))]
    [System.Xml.Serialization.XmlElementAttribute("figure", typeof(figure))]
    [System.Xml.Serialization.XmlElementAttribute("sourcecode", typeof(sourcecode))]

    [System.Xml.Serialization.XmlElementAttribute("eref", typeof(eref))]
    [System.Xml.Serialization.XmlElementAttribute("iref", typeof(iref))]
    [System.Xml.Serialization.XmlElementAttribute("relref", typeof(relref))]
    [System.Xml.Serialization.XmlElementAttribute("cref", typeof(cref))]
    [System.Xml.Serialization.XmlElementAttribute("xref", typeof(xref))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceTextRun[] ItemsElementName { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pn { get; set; }
    }
#endregion
#region // artwork
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class artwork : Common {

    /// <remarks/>
    
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any { get; set; }

    [System.Xml.Serialization.XmlTextAttribute()]
    public string Text { get; set; } = "";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string pn { get; set; } = "";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string name { get; set; } = "";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string type { get; set; } = "";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(alignType.Left)]
    public alignType align { get; set; } = alignType.Left;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string alt { get; set; } = "";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string width { get; set; } = "";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string height { get; set; } = "";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string src { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string originalSrc { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute()]
public enum alignType {

    /// <remarks/>
    [XmlEnum(Name = "left")]
    Left,

    /// <remarks/>
    [XmlEnum(Name = "center")]
    Center,

    /// <remarks/>
    [XmlEnum(Name = "right")]
    Right,
    }

#endregion
#region // annotation

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class cref : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("em", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("eref", typeof(eref))]
    [System.Xml.Serialization.XmlElementAttribute("relref", typeof(relref))]
    [System.Xml.Serialization.XmlElementAttribute("strong", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("sub", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("sup", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("tt", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("xref", typeof(xref))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceTextRun[] ItemsElementName { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string source { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.True)]
    public boolean display { get; set; } = boolean.True;
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute()]
[System.Xml.Serialization.XmlRootAttribute("tt", IsNullable = false)]
public partial class textrun : Common{

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("bcp14", typeof(Bcp14String))]
    [System.Xml.Serialization.XmlElementAttribute("em", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("strong", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("sub", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("sup", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("cref", typeof(cref))]
    [System.Xml.Serialization.XmlElementAttribute("eref", typeof(eref))]
    [System.Xml.Serialization.XmlElementAttribute("iref", typeof(iref))]
    [System.Xml.Serialization.XmlElementAttribute("xref", typeof(xref))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceTextRun[] ItemsElementName { get; set; }

    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class eref : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string target { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Text { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class iref : Common {
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string item { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string subitem { get; set; } = "";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.False)]
    public boolean primary { get; set; } = boolean.False;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pn { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute()]
public enum boolean {

    /// <remarks/>
    [XmlEnum(Name = "true")]
    True,

    /// <remarks/>
    [XmlEnum(Name = "false")]
    False,
    }



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class xref : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "IDREF")]
    public string target { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.False)]
    public boolean pageno { get; set; } = boolean.False;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(xrefFormat.Default)]
    public xrefFormat format { get; set; } = xrefFormat.Default;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string derivedContent { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Text { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum xrefFormat {

    /// <remarks/>
    [XmlEnum(Name = "counter")]
    Counter,

    /// <remarks/>
    [XmlEnum(Name = "title")]
    Title,

    /// <remarks/>
    [XmlEnum(Name = "none")]
    None,

    /// <remarks/>
    [XmlEnum(Name = "default")]
    Default,
    }


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class relref : Common {
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "IDREF")]
    public string target { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(relrefDisplayFormat.Of)]
    public relrefDisplayFormat displayFormat { get; set; } = relrefDisplayFormat.Of;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string section { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string relative { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Text { get; set; }


    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string derivedLink { get; set; }


    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum relrefDisplayFormat {

    /// <remarks/>
    [XmlEnum(Name = "of")]
    Of,

    /// <remarks/>
    [XmlEnum(Name = "comma")]
    Comma,

    /// <remarks/>
    [XmlEnum(Name = "parens")]
    Parens,

    /// <remarks/>
    [XmlEnum(Name = "bare")]
    Bare,
    }


#endregion
#region // figure

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class figure : Common {


    /// <remarks/>
    public name name { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("iref")]
    public iref[] iref { get; set; }

    /// <remarks/>
    public textrun preamble { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("artwork", typeof(artwork))]
    [System.Xml.Serialization.XmlElementAttribute("sourcecode", typeof(sourcecode))]
    public object[] Items { get; set; }

    /// <remarks/>
    public postamble postamble { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }


    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string width { get; set; } = "";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string height { get; set; } = "";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pn { get; set; }

    // Deprecated

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string title { get; set; } = "";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("suppress-title")]
    [System.ComponentModel.DefaultValueAttribute(boolean.False)]
    public boolean suppresstitle { get; set; } = boolean.False;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(alignType.Left)]
    public alignType align { get; set; } = alignType.Left;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string alt { get; set; } = "";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string src { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string originalSrc { get; set; }
    }

#endregion
#region // name

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class name : Common {
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("cref", typeof(cref))]
    [System.Xml.Serialization.XmlElementAttribute("eref", typeof(eref))]
    [System.Xml.Serialization.XmlElementAttribute("relref", typeof(relref))]
    [System.Xml.Serialization.XmlElementAttribute("tt", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("xref", typeof(xref))]
    public object[] Items { get; set; }


    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string slugifiedName { get; set; }
    }

#endregion
#region // sourcecode

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class sourcecode : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string pn { get; set; } = "";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string name { get; set; } = "";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string type { get; set; } = "";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string src { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string originalSrc { get; set; }
    }

#endregion
#region // postamble

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class postamble : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("cref", typeof(cref))]
    [System.Xml.Serialization.XmlElementAttribute("eref", typeof(eref))]
    [System.Xml.Serialization.XmlElementAttribute("iref", typeof(iref))]
    [System.Xml.Serialization.XmlElementAttribute("spanx", typeof(spanx))]
    [System.Xml.Serialization.XmlElementAttribute("xref", typeof(xref))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceTextRun[] ItemsElementName { get; set; }
    }

#endregion
#region // spanx

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class spanx : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
    public string space { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("emph")]
    public string style { get; set; } = "emph";

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Text { get; set; }
    }

#endregion
#region // List

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class list : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("t")]
    public t[] t { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("empty")]
    public string style { get; set; } = "empty";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hangIndent { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string counter { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pn { get; set; }
    }

#endregion
#region // t


public partial class Bcp14String {
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Text { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class t : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(typeof(string))] 
    [System.Xml.Serialization.XmlElementAttribute("bcp14", typeof(Bcp14String))]
    [System.Xml.Serialization.XmlElementAttribute("cref", typeof(cref))]
    [System.Xml.Serialization.XmlElementAttribute("em", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("eref", typeof(eref))]
    [System.Xml.Serialization.XmlElementAttribute("iref", typeof(iref))]
    [System.Xml.Serialization.XmlElementAttribute("list", typeof(list))]
    [System.Xml.Serialization.XmlElementAttribute("relref", typeof(relref))]
    [System.Xml.Serialization.XmlElementAttribute("spanx", typeof(spanx))]
    [System.Xml.Serialization.XmlElementAttribute("strong", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("sub", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("sup", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("tt", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("vspace", typeof(vspace))]
    [System.Xml.Serialization.XmlElementAttribute("xref", typeof(xref))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceTextRun[] ItemsElementName { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pn { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hangText { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.False)]
    public boolean keepWithNext { get; set; } = boolean.False;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.False)]
    public boolean keepWithPrevious { get; set; } = boolean.False;

    }



#endregion
#region // vspace

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class vspace {

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("0")]
    public string blankLines { get; set; } = "0";
    }


#endregion
#region // OL


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class ol : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("li")]
    public listItemType[] li { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string type { get; set; } = "1";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string start { get; set; } = "1";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string group { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(olSpacing.Normal)]
    public olSpacing spacing { get; set; } = olSpacing.Normal;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pn { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum olSpacing {

    /// <remarks/>
    [XmlEnum(Name = "normal")]
    Normal,

    /// <remarks/>
    [XmlEnum(Name = "compact")]
    Compact,
    }

#endregion
#region // UL


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class ul : Common {
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("li")]
    public listItemType[] li { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ulSpacing.Normal)]
    public ulSpacing spacing { get; set; } = ulSpacing.Normal;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolean empty { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool emptySpecified { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pn { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum ulSpacing {

    /// <remarks/>
    [XmlEnum(Name = "normal")]
    Normal,

    /// <remarks/>
    [XmlEnum(Name = "compact")]
    Compact,
    }


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum dlSpacing {

    /// <remarks/>
    [XmlEnum(Name = "normal")]
    Normal,

    /// <remarks/>
    [XmlEnum(Name = "compact")]
    Compact,
    }

#endregion
#region // Note


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class note : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dl", typeof(dl))]
    [System.Xml.Serialization.XmlElementAttribute("ol", typeof(ol))]
    [System.Xml.Serialization.XmlElementAttribute("t", typeof(t))]
    [System.Xml.Serialization.XmlElementAttribute("ul", typeof(ul))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceTextRun[] ItemsElementName { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pn { get; set; }
    }

#endregion
#region // Boilerplate

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class boilerplate : Common {
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("section")]
    public section[] section { get; set; }

    }

#endregion
#region // Section

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class section : Common {

    /// <remarks/>
    public name name { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("artwork", typeof(artwork))]
    [System.Xml.Serialization.XmlElementAttribute("aside", typeof(aside))]
    [System.Xml.Serialization.XmlElementAttribute("blockquote", typeof(blockquote))]
    [System.Xml.Serialization.XmlElementAttribute("dl", typeof(dl))]
    [System.Xml.Serialization.XmlElementAttribute("figure", typeof(figure))]
    [System.Xml.Serialization.XmlElementAttribute("iref", typeof(iref))]
    [System.Xml.Serialization.XmlElementAttribute("ol", typeof(ol))]
    [System.Xml.Serialization.XmlElementAttribute("sourcecode", typeof(sourcecode))]
    [System.Xml.Serialization.XmlElementAttribute("t", typeof(t))]
    [System.Xml.Serialization.XmlElementAttribute("table", typeof(table))]
    [System.Xml.Serialization.XmlElementAttribute("texttable", typeof(texttable))]
    [System.Xml.Serialization.XmlElementAttribute("ul", typeof(ul))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]

    public object[] Items { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceTextRun[] ItemsElementName { get; set; }


    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("section")]
    public section[] section1 { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pn { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.True)]
    public boolean numbered { get; set; } = boolean.True;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(sectionToc.Default)]
    public sectionToc toc { get; set; } = sectionToc.Default;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(boolean.False)]
    public boolean removeInRFC { get; set; } = boolean.False;
    }

#endregion
#region // Aside

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class aside : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("artwork", typeof(artwork))]
    [System.Xml.Serialization.XmlElementAttribute("dl", typeof(dl))]
    [System.Xml.Serialization.XmlElementAttribute("figure", typeof(figure))]
    [System.Xml.Serialization.XmlElementAttribute("iref", typeof(iref))]
    [System.Xml.Serialization.XmlElementAttribute("list", typeof(list))]
    [System.Xml.Serialization.XmlElementAttribute("t", typeof(t))]
    [System.Xml.Serialization.XmlElementAttribute("table", typeof(table))]
    [System.Xml.Serialization.XmlElementAttribute("ul", typeof(ul))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceTextRun[] ItemsElementName { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pn { get; set; }
    }

#endregion
#region // Table


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class table : Common {

    /// <remarks/>
    public name name { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("iref")]
    public iref[] iref { get; set; }

    /// <remarks/>
    public tableRowsType thead { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tbody")]
    public tableRowsType[] tbody { get; set; }

    /// <remarks/>
    public tableRowsType tfoot { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pn { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute()]
[System.Xml.Serialization.XmlRootAttribute("thead", IsNullable = false)]
public partial class tableRowsType : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tr")]
    public tr[] tr { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class tr : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("td", typeof(tableCellType))]
    [System.Xml.Serialization.XmlElementAttribute("th", typeof(tableCellType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public tableCellType[] Items { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType6[] ItemsElementName { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute()]
[System.Xml.Serialization.XmlRootAttribute("td", IsNullable = false)]
public partial class tableCellType : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("artwork", typeof(artwork))]
    [System.Xml.Serialization.XmlElementAttribute("bcp14", typeof(Bcp14String))]
    [System.Xml.Serialization.XmlElementAttribute("cref", typeof(cref))]
    [System.Xml.Serialization.XmlElementAttribute("dl", typeof(dl))]
    [System.Xml.Serialization.XmlElementAttribute("em", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("eref", typeof(eref))]
    [System.Xml.Serialization.XmlElementAttribute("figure", typeof(figure))]
    [System.Xml.Serialization.XmlElementAttribute("iref", typeof(iref))]
    [System.Xml.Serialization.XmlElementAttribute("ol", typeof(ol))]
    [System.Xml.Serialization.XmlElementAttribute("relref", typeof(relref))]
    [System.Xml.Serialization.XmlElementAttribute("sourcecode", typeof(sourcecode))]
    [System.Xml.Serialization.XmlElementAttribute("strong", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("sub", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("sup", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("t", typeof(t))]
    [System.Xml.Serialization.XmlElementAttribute("tt", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("ul", typeof(ul))]
    [System.Xml.Serialization.XmlElementAttribute("xref", typeof(xref))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceTextRun[] ItemsElementName { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string colspan { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rowspan { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public alignType align { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool alignSpecified { get; set; }
    }



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
public enum ItemsChoiceType6 {

    /// <remarks/>
    [XmlEnum(Name = "td")]
    Td,

    /// <remarks/>
    [XmlEnum(Name = "th")]
    Th,
    }


#endregion
#region // Blockquote

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class blockquote : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("artwork", typeof(artwork))]
    [System.Xml.Serialization.XmlElementAttribute("bcp14", typeof(Bcp14String))]
    [System.Xml.Serialization.XmlElementAttribute("cref", typeof(cref))]
    [System.Xml.Serialization.XmlElementAttribute("dl", typeof(dl))]
    [System.Xml.Serialization.XmlElementAttribute("em", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("eref", typeof(eref))]
    [System.Xml.Serialization.XmlElementAttribute("figure", typeof(figure))]
    [System.Xml.Serialization.XmlElementAttribute("iref", typeof(iref))]
    [System.Xml.Serialization.XmlElementAttribute("list", typeof(list))]
    [System.Xml.Serialization.XmlElementAttribute("ol", typeof(ol))]
    [System.Xml.Serialization.XmlElementAttribute("relref", typeof(relref))]
    [System.Xml.Serialization.XmlElementAttribute("sourcecode", typeof(sourcecode))]
    [System.Xml.Serialization.XmlElementAttribute("strong", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("sub", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("sup", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("t", typeof(t))]
    [System.Xml.Serialization.XmlElementAttribute("tt", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("ul", typeof(ul))]
    [System.Xml.Serialization.XmlElementAttribute("xref", typeof(xref))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceTextRun[] ItemsElementName { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pn { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cite { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string quotedFrom { get; set; }
    }


#endregion
#region // Texttable


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]

public partial class texttable {

    /// <remarks/>
    public textrun preamble { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ttcol")]
    public ttcol[] ttcol { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("c")]
    public c[] c { get; set; }

    /// <remarks/>
    public postamble postamble { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string title { get; set; } = "";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("suppress-title")]
    [System.ComponentModel.DefaultValueAttribute(boolean.False)]
    public boolean suppresstitle { get; set; } = boolean.False;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(alignType.Center)]
    public alignType align { get; set; } = alignType.Center;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(texttableStyle.Full)]
    public texttableStyle style { get; set; } = texttableStyle.Full;
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class ttcol {

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string width { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ttcolAlign.Left)]
    public ttcolAlign align { get; set; } = ttcolAlign.Left;

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum ttcolAlign {

    /// <remarks/>
    [XmlEnum(Name = "left")]
    Left,

    /// <remarks/>
    [XmlEnum(Name = "center")]
    Center,

    /// <remarks/>
    [XmlEnum(Name = "right")]
    Right,
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class c {

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("cref", typeof(cref))]
    [System.Xml.Serialization.XmlElementAttribute("eref", typeof(eref))]
    [System.Xml.Serialization.XmlElementAttribute("iref", typeof(iref))]
    [System.Xml.Serialization.XmlElementAttribute("spanx", typeof(spanx))]
    [System.Xml.Serialization.XmlElementAttribute("xref", typeof(xref))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]

    public object[] Items { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceTextRun[] ItemsElementName { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum texttableStyle {

    /// <remarks/>
    [XmlEnum(Name = "all")]
    All,

    /// <remarks/>
    [XmlEnum(Name = "none")]
    None,

    /// <remarks/>
    [XmlEnum(Name = "headers")]
    Headers,

    /// <remarks/>
    [XmlEnum(Name = "full")]
    Full,
    }

#endregion
#region // Toc



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum sectionToc {

    /// <remarks/>
    [XmlEnum(Name = "include")]
    Include,

    /// <remarks/>
    [XmlEnum(Name = "exclude")]
    Exclude,

    /// <remarks/>
    [XmlEnum(Name = "default")]
    Default,
    }

#endregion
#region // Middle



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class middle : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("section")]
    public section[] section { get; set; }
    }

#endregion
#region // Back

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class back {

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("displayreference")]
    public displayreference[] displayreference { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("references")]
    public references[] references { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("section")]
    public section[] section { get; set; }
    }

#endregion
#region // display reference


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class displayreference {

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string target { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string to { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class references {

    /// <remarks/>
    public name name { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("reference", typeof(reference))]
    [System.Xml.Serialization.XmlElementAttribute("referencegroup", typeof(referencegroup))]
    public object[] Items { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("References")]
    public string title { get; set; } = "References";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string pn { get; set; } = "";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }
    }

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class reference {

    /// <remarks/>
    public front front { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("annotation", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("format", typeof(format))]
    [System.Xml.Serialization.XmlElementAttribute("refcontent", typeof(refcontent))]
    [System.Xml.Serialization.XmlElementAttribute("seriesInfo", typeof(seriesInfo))]
    public object[] Items { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string target { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public boolean quoteTitle { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool quoteTitleSpecified { get; set; }
    }

#endregion
#region // format


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class format {
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string target { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string octets { get; set; }
    }

#endregion
#region // Refcontent


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class refcontent : Common {

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("bcp14", typeof(Bcp14String))]
    [System.Xml.Serialization.XmlElementAttribute("em", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("strong", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("sub", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("sup", typeof(textrun))]
    [System.Xml.Serialization.XmlElementAttribute("tt", typeof(textrun))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceTextRun[] ItemsElementName { get; set; }


    }


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class referencegroup {

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("reference")]
    public reference[] reference { get; set; }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string anchor { get; set; }
    }

#endregion
#region // Consensus


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum rfcConsensus {

    /// <remarks/>
    [XmlEnum(Name = "no")]
    No,

    /// <remarks/>
    [XmlEnum(Name = "yes")]
    Yes,

    /// <remarks/>
    [XmlEnum(Name = "true")]
    True,

    /// <remarks/>
    [XmlEnum(Name = "false")]
    False,
    }

#endregion
#region // Index include

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum rfcIndexInclude {

    /// <remarks/>
    [XmlEnum(Name = "true")]
    True,

    /// <remarks/>
    [XmlEnum(Name = "false")]
    False,
    }

#endregion

